// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH-zFZNSxnbbe4scOG-d0-gPOUYjd5NC8',
    appId: '1:687343960627:web:18911301b3bb5f27805946',
    messagingSenderId: '687343960627',
    projectId: 'ecommerce-a3aa5',
    authDomain: 'ecommerce-a3aa5.firebaseapp.com',
    storageBucket: 'ecommerce-a3aa5.appspot.com',
    measurementId: 'G-3GER51M9ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9DNazgHQCviAu-tpVn6yc3ZGdfsPdeps',
    appId: '1:687343960627:android:95dd5b3fe3159c78805946',
    messagingSenderId: '687343960627',
    projectId: 'ecommerce-a3aa5',
    storageBucket: 'ecommerce-a3aa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL85I77Shu5VRVhVpakhasy636hljBx2M',
    appId: '1:687343960627:ios:89a52d03823d8305805946',
    messagingSenderId: '687343960627',
    projectId: 'ecommerce-a3aa5',
    storageBucket: 'ecommerce-a3aa5.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL85I77Shu5VRVhVpakhasy636hljBx2M',
    appId: '1:687343960627:ios:16484681c23abe5d805946',
    messagingSenderId: '687343960627',
    projectId: 'ecommerce-a3aa5',
    storageBucket: 'ecommerce-a3aa5.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
